import Vue from 'vue'
import Router from 'vue-router'
import Index from '@/components/index'

Vue.use(Router)

export default new Router({
  routes: [
    {
      path: '/',
      name: '叶菜',
      component: Index,
      redirect:'/jmc/date',
      children:[
        {
        path:'/jmc',
        redirect:'/jmc/date',
        name:"鸡毛菜",
        component:resolve=>require(["../components/blank.vue"],resolve),
        children:[
          {
            path:'date',
            name:'鸡毛菜-date',
            component:resolve=>require(["../components/date.vue"],resolve),
          },
          {
            path:'month',
            name:'鸡毛菜-month',
            component:resolve=>require(["../components/month.vue"],resolve),
          },
          {
            path:'monthly',
            name:'鸡毛菜-monthly',
            component:resolve=>require(["../components/monthly.vue"],resolve),
          }]},
          {
            path:'/th',
            redirect:'/th/date',
            name:"茼蒿",
            component:resolve=>require(["../components/blank.vue"],resolve),
            children:[
              {
                path:'date',
                name:'茼蒿-date',
                component:resolve=>require(["../components/date.vue"],resolve),
              },
              {
                path:'month',
                name:'茼蒿-month',
                component:resolve=>require(["../components/month.vue"],resolve),
              },
              {
                path:'monthly',
                name:'茼蒿-monthly',
                component:resolve=>require(["../components/monthly.vue"],resolve),
              },
        ]
      },
      {
        path:'/ymc',
        redirect:'/ymc/date',
        name:"油麦菜",
        component:resolve=>require(["../components/blank.vue"],resolve),
        children:[
          {
            path:'date',
            name:'油麦菜-date',
            component:resolve=>require(["../components/date.vue"],resolve),
          },
          {
            path:'month',
            name:'油麦菜-month',
            component:resolve=>require(["../components/month.vue"],resolve),
          },
          {
            path:'monthly',
            name:'油麦菜-monthly',
            component:resolve=>require(["../components/monthly.vue"],resolve),
          },]},
  {
        path:'/cbc',
        redirect:'/cbc/date',
        name:"长菠菜",
        component:resolve=>require(["../components/blank.vue"],resolve),
        children:[
          {
            path:'date',
            name:'长菠菜-date',
            component:resolve=>require(["../components/date.vue"],resolve),
          },
          {
            path:'month',
            name:'长菠菜-month',
            component:resolve=>require(["../components/month.vue"],resolve),
          },
          {
            path:'monthly',
            name:'长菠菜-monthly',
            component:resolve=>require(["../components/monthly.vue"],resolve),
          },
        ]
      },{
        path:'/xbc',
        redirect:'/xbc/date',
        name:"小菠菜",
        component:resolve=>require(["../components/blank.vue"],resolve),
        children:[
          {
            path:'date',
            name:'小菠菜-date',
            component:resolve=>require(["../components/date.vue"],resolve),
          },
          {
            path:'month',
            name:'小菠菜-month',
            component:resolve=>require(["../components/month.vue"],resolve),
          },
          {
            path:'monthly',
            name:'小菠菜-monthly',
            component:resolve=>require(["../components/monthly.vue"],resolve),
          },
        ]
      },{
        path:'/hbc',
        redirect:'/hbc/date',
        name:"小白菜杭白菜",
        component:resolve=>require(["../components/blank.vue"],resolve),
        children:[
          {
            path:'date',
            name:'小白菜杭白菜-date',
            component:resolve=>require(["../components/date.vue"],resolve),
          },
          {
            path:'month',
            name:'小白菜杭白菜-month',
            component:resolve=>require(["../components/month.vue"],resolve),
          },
          {
            path:'monthly',
            name:'小白菜杭白菜-monthly',
            component:resolve=>require(["../components/monthly.vue"],resolve),
          },
        ]
      },{
        path:'/qc',
        redirect:'/qc/date',
        name:"青菜",
        component:resolve=>require(["../components/blank.vue"],resolve),
        children:[
          {
            path:'date',
            name:'青菜-date',
            component:resolve=>require(["../components/date.vue"],resolve),
          },
          {
            path:'month',
            name:'青菜-month',
            component:resolve=>require(["../components/month.vue"],resolve),
          },
          {
            path:'monthly',
            name:'青菜-monthly',
            component:resolve=>require(["../components/monthly.vue"],resolve),
          },
        ]
      },{
        path:'/jc',
        redirect:'/jc/date',
        name:"荠菜",
        component:resolve=>require(["../components/blank.vue"],resolve),
        children:[
          {
            path:'date',
            name:'荠菜-date',
            component:resolve=>require(["../components/date.vue"],resolve),
          },
          {
            path:'month',
            name:'荠菜-month',
            component:resolve=>require(["../components/month.vue"],resolve),
          },
          {
            path:'monthly',
            name:'荠菜-monthly',
            component:resolve=>require(["../components/monthly.vue"],resolve),
          },
        ]
      },{
        path:'/xc',
        redirect:'/xc/date',
        name:"苋菜",
        component:resolve=>require(["../components/blank.vue"],resolve),
        children:[
          {
            path:'date',
            name:'苋菜-date',
            component:resolve=>require(["../components/date.vue"],resolve),
          },
          {
            path:'month',
            name:'苋菜-month',
            component:resolve=>require(["../components/month.vue"],resolve),
          },
          {
            path:'monthly',
            name:'苋菜-monthly',
            component:resolve=>require(["../components/monthly.vue"],resolve),
          },
        ]
      },{
        path:'/xiangc',
        redirect:'/xiangc/date',
        name:"香菜",
        component:resolve=>require(["../components/blank.vue"],resolve),
        children:[
          {
            path:'date',
            name:'香菜-date',
            component:resolve=>require(["../components/date.vue"],resolve),
          },
          {
            path:'month',
            name:'香菜-month',
            component:resolve=>require(["../components/month.vue"],resolve),
          },
          {
            path:'monthly',
            name:'香菜-monthly',
            component:resolve=>require(["../components/monthly.vue"],resolve),
          },
        ]
      },{
        path:'/sc',
        redirect:'/sc/date',
        name:"生菜",
        component:resolve=>require(["../components/blank.vue"],resolve),
        children:[
          {
            path:'date',
            name:'生菜-date',
            component:resolve=>require(["../components/date.vue"],resolve),
          },
          {
            path:'month',
            name:'生菜-month',
            component:resolve=>require(["../components/month.vue"],resolve),
          },
          {
            path:'monthly',
            name:'生菜-monthly',
            component:resolve=>require(["../components/monthly.vue"],resolve),
          },
        ]
      },{
        path:'/jiec',
        redirect:'/jiec/date',
        name:"芥菜",
        component:resolve=>require(["../components/blank.vue"],resolve),
        children:[
          {
            path:'date',
            name:'芥菜-date',
            component:resolve=>require(["../components/date.vue"],resolve),
          },
          {
            path:'month',
            name:'芥菜-month',
            component:resolve=>require(["../components/month.vue"],resolve),
          },
          {
            path:'monthly',
            name:'芥菜-monthly',
            component:resolve=>require(["../components/monthly.vue"],resolve),
          },
        ]
      },{
        path:'/wdm',
        redirect:'/wdm/date',
        name:"豌豆苗",
        component:resolve=>require(["../components/blank.vue"],resolve),
        children:[
          {
            path:'date',
            name:'豌豆苗-date',
            component:resolve=>require(["../components/date.vue"],resolve),
          },
          {
            path:'month',
            name:'豌豆苗-month',
            component:resolve=>require(["../components/month.vue"],resolve),
          },
          {
            path:'monthly',
            name:'豌豆苗-monthly',
            component:resolve=>require(["../components/monthly.vue"],resolve),
          },
        ]
      },{
        path:'/xxc',
        redirect:'/xxc/date',
        name:"小香蔥",
        component:resolve=>require(["../components/blank.vue"],resolve),
        children:[
          {
            path:'date',
            name:'小香蔥-date',
            component:resolve=>require(["../components/date.vue"],resolve),
          },
          {
            path:'month',
            name:'小香蔥-month',
            component:resolve=>require(["../components/month.vue"],resolve),
          },
          {
            path:'monthly',
            name:'小香蔥-monthly',
            component:resolve=>require(["../components/monthly.vue"],resolve),
          },
        ]
      },{
        path:'/kxc',
        redirect:'/kxc/date',
        name:"空心菜",
        component:resolve=>require(["../components/blank.vue"],resolve),
        children:[
          {
            path:'date',
            name:'空心菜-date',
            component:resolve=>require(["../components/date.vue"],resolve),
          },
          {
            path:'month',
            name:'空心菜-month',
            component:resolve=>require(["../components/month.vue"],resolve),
          },
          {
            path:'monthly',
            name:'空心菜-monthly',
            component:resolve=>require(["../components/monthly.vue"],resolve),
          },
        ]
      },{
        path:'/jl',
        redirect:'/jl/date',
        name:"芥蓝",
        component:resolve=>require(["../components/blank.vue"],resolve),
        children:[
          {
            path:'date',
            name:'芥蓝-date',
            component:resolve=>require(["../components/date.vue"],resolve),
          },
          {
            path:'month',
            name:'芥蓝-month',
            component:resolve=>require(["../components/month.vue"],resolve),
          },
          {
            path:'monthly',
            name:'芥蓝-monthly',
            component:resolve=>require(["../components/monthly.vue"],resolve),
          },
        ]
      },{
        path:'/ct',
        redirect:'/ct/date',
        name:"草头",
        component:resolve=>require(["../components/blank.vue"],resolve),
        children:[
          {
            path:'date',
            name:'草头-date',
            component:resolve=>require(["../components/date.vue"],resolve),
          },
          {
            path:'month',
            name:'草头-month',
            component:resolve=>require(["../components/month.vue"],resolve),
          },
          {
            path:'monthly',
            name:'草头-monthly',
            component:resolve=>require(["../components/monthly.vue"],resolve),
          },
        ]
      },{
        path:'/jh',
        redirect:'/jh/date',
        name:"韭黄",
        component:resolve=>require(["../components/blank.vue"],resolve),
        children:[
          {
            path:'date',
            name:'韭黄-date',
            component:resolve=>require(["../components/date.vue"],resolve),
          },
          {
            path:'month',
            name:'韭黄-month',
            component:resolve=>require(["../components/month.vue"],resolve),
          },
          {
            path:'monthly',
            name:'韭黄-monthly',
            component:resolve=>require(["../components/monthly.vue"],resolve),
          },
        ]
      },{
        path:'/jiuc',
        redirect:'/jiuc/date',
        name:"韭菜",
        component:resolve=>require(["../components/blank.vue"],resolve),
        children:[
          {
            path:'date',
            name:'韭菜-date',
            component:resolve=>require(["../components/date.vue"],resolve),
          },
          {
            path:'month',
            name:'韭菜-month',
            component:resolve=>require(["../components/month.vue"],resolve),
          },
          {
            path:'monthly',
            name:'韭菜-monthly',
            component:resolve=>require(["../components/monthly.vue"],resolve),
          },
        ]
      },{
        path:'/mlt',
        redirect:'/mlt/date',
        name:"马兰头",
        component:resolve=>require(["../components/blank.vue"],resolve),
        children:[
          {
            path:'date',
            name:'马兰头-date',
            component:resolve=>require(["../components/date.vue"],resolve),
          },
          {
            path:'month',
            name:'马兰头-month',
            component:resolve=>require(["../components/month.vue"],resolve),
          },
          {
            path:'monthly',
            name:'马兰头-monthly',
            component:resolve=>require(["../components/monthly.vue"],resolve),
          },
        ]
      },{
        path:'/phc',
        redirect:'/phc/date',
        name:"蓬花菜",
        component:resolve=>require(["../components/blank.vue"],resolve),
        children:[
          {
            path:'date',
            name:'蓬花菜-date',
            component:resolve=>require(["../components/date.vue"],resolve),
          },
          {
            path:'month',
            name:'蓬花菜-month',
            component:resolve=>require(["../components/month.vue"],resolve),
          },
          {
            path:'monthly',
            name:'蓬花菜-monthly',
            component:resolve=>require(["../components/monthly.vue"],resolve),
          },
        ]
      },
    ]
    },    {
      path: '/',
      name: '茄果',
      component: Index,
      redirect:'/fq',
      children:[
        {
          path:'/fq',
          redirect:'/fq/date',
          name:"番茄",
          component:resolve=>require(["../components/blank.vue"],resolve),
          children:[
            {
              path:'date',
              name:'番茄-date',
              component:resolve=>require(["../components/date.vue"],resolve),
            },
            {
              path:'month',
              name:'番茄-month',
              component:resolve=>require(["../components/month.vue"],resolve),
            },
            {
              path:'monthly',
              name:'番茄-monthly',
              component:resolve=>require(["../components/monthly.vue"],resolve),
            }
          ]
        },{
          path:'/hg',
          redirect:'/hg/date',
          name:"黄瓜",
          component:resolve=>require(["../components/blank.vue"],resolve),
          children:[
            {
              path:'date',
              name:'黄瓜-date',
              component:resolve=>require(["../components/date.vue"],resolve),
            },
            {
              path:'month',
              name:'黄瓜-month',
              component:resolve=>require(["../components/month.vue"],resolve),
            },
            {
              path:'monthly',
              name:'黄瓜-monthly',
              component:resolve=>require(["../components/monthly.vue"],resolve),
            }
          ]
        },{
          path:'/kg',
          redirect:'/kg/date',
          name:"苦瓜",
          component:resolve=>require(["../components/blank.vue"],resolve),
          children:[
            {
              path:'date',
              name:'苦瓜-date',
              component:resolve=>require(["../components/date.vue"],resolve),
            },
            {
              path:'month',
              name:'苦瓜-month',
              component:resolve=>require(["../components/month.vue"],resolve),
            },
            {
              path:'monthly',
              name:'苦瓜-monthly',
              component:resolve=>require(["../components/monthly.vue"],resolve),
            }
          ]
        },{
          path:'/sg',
          redirect:'/sg/date',
          name:"丝瓜",
          component:resolve=>require(["../components/blank.vue"],resolve),
          children:[
            {
              path:'date',
              name:'丝瓜-date',
              component:resolve=>require(["../components/date.vue"],resolve),
            },
            {
              path:'month',
              name:'丝瓜-month',
              component:resolve=>require(["../components/month.vue"],resolve),
            },
            {
              path:'monthly',
              name:'丝瓜-monthly',
              component:resolve=>require(["../components/monthly.vue"],resolve),
            }
          ]
        },{
          path:'/xhl',
          redirect:'/xhl/date',
          name:"西葫芦",
          component:resolve=>require(["../components/blank.vue"],resolve),
          children:[
            {
              path:'date',
              name:'西葫芦-date',
              component:resolve=>require(["../components/date.vue"],resolve),
            },
            {
              path:'month',
              name:'西葫芦-month',
              component:resolve=>require(["../components/month.vue"],resolve),
            },
            {
              path:'monthly',
              name:'西葫芦-monthly',
              component:resolve=>require(["../components/monthly.vue"],resolve),
            }
          ]
        },{
          path:'/qz',
          redirect:'/qz/date',
          name:"茄子",
          component:resolve=>require(["../components/blank.vue"],resolve),
          children:[
            {
              path:'date',
              name:'茄子-date',
              component:resolve=>require(["../components/date.vue"],resolve),
            },
            {
              path:'month',
              name:'茄子-month',
              component:resolve=>require(["../components/month.vue"],resolve),
            },
            {
              path:'monthly',
              name:'茄子-monthly',
              component:resolve=>require(["../components/monthly.vue"],resolve),
            }
          ]
        },{
          path:'/cyj',
          redirect:'/cyj/date',
          name:"彩圆椒",
          component:resolve=>require(["../components/blank.vue"],resolve),
          children:[
            {
              path:'date',
              name:'彩圆椒-date',
              component:resolve=>require(["../components/date.vue"],resolve),
            },
            {
              path:'month',
              name:'彩圆椒-month',
              component:resolve=>require(["../components/month.vue"],resolve),
            },
            {
              path:'monthly',
              name:'彩圆椒-monthly',
              component:resolve=>require(["../components/monthly.vue"],resolve),
            }
          ]
        },{
          path:'/yj',
          redirect:'/yj/date',
          name:"圆椒",
          component:resolve=>require(["../components/blank.vue"],resolve),
          children:[
            {
              path:'date',
              name:'圆椒-date',
              component:resolve=>require(["../components/date.vue"],resolve),
            },
            {
              path:'month',
              name:'圆椒-month',
              component:resolve=>require(["../components/month.vue"],resolve),
            },
            {
              path:'monthly',
              name:'圆椒-monthly',
              component:resolve=>require(["../components/monthly.vue"],resolve),
            }
          ]
        },{
          path:'/qjj',
          redirect:'/qjj/date',
          name:"青尖椒",
          component:resolve=>require(["../components/blank.vue"],resolve),
          children:[
            {
              path:'date',
              name:'青尖椒-date',
              component:resolve=>require(["../components/date.vue"],resolve),
            },
            {
              path:'month',
              name:'青尖椒-month',
              component:resolve=>require(["../components/month.vue"],resolve),
            },
            {
              path:'monthly',
              name:'青尖椒-monthly',
              component:resolve=>require(["../components/monthly.vue"],resolve),
            }
          ]
        },{
          path:'/hjj',
          redirect:'/hjj/date',
          name:"红尖椒",
          component:resolve=>require(["../components/blank.vue"],resolve),
          children:[
            {
              path:'date',
              name:'红尖椒-date',
              component:resolve=>require(["../components/date.vue"],resolve),
            },
            {
              path:'month',
              name:'红尖椒-month',
              component:resolve=>require(["../components/month.vue"],resolve),
            },
            {
              path:'monthly',
              name:'红尖椒-monthly',
              component:resolve=>require(["../components/monthly.vue"],resolve),
            }
          ]
        },{
          path:'/hld',
          redirect:'/hld/date',
          name:"荷兰豆",
          component:resolve=>require(["../components/blank.vue"],resolve),
          children:[
            {
              path:'date',
              name:'荷兰豆-date',
              component:resolve=>require(["../components/date.vue"],resolve),
            },
            {
              path:'month',
              name:'荷兰豆-month',
              component:resolve=>require(["../components/month.vue"],resolve),
            },
            {
              path:'monthly',
              name:'荷兰豆-monthly',
              component:resolve=>require(["../components/monthly.vue"],resolve),
            }
          ]
        },{
          path:'/wd',
          redirect:'/wd/date',
          name:"豌豆",
          component:resolve=>require(["../components/blank.vue"],resolve),
          children:[
            {
              path:'date',
              name:'豌豆-date',
              component:resolve=>require(["../components/date.vue"],resolve),
            },
            {
              path:'month',
              name:'豌豆-month',
              component:resolve=>require(["../components/month.vue"],resolve),
            },
            {
              path:'monthly',
              name:'豌豆-monthly',
              component:resolve=>require(["../components/monthly.vue"],resolve),
            }
          ]
        },{
          path:'/cd',
          redirect:'/cd/date',
          name:"蚕豆",
          component:resolve=>require(["../components/blank.vue"],resolve),
          children:[
            {
              path:'date',
              name:'蚕豆-date',
              component:resolve=>require(["../components/date.vue"],resolve),
            },
            {
              path:'month',
              name:'蚕豆-month',
              component:resolve=>require(["../components/month.vue"],resolve),
            },
            {
              path:'monthly',
              name:'蚕豆-monthly',
              component:resolve=>require(["../components/monthly.vue"],resolve),
            }
          ]
        },{
          path:'/ng',
          redirect:'/ng/date',
          name:"南瓜",
          component:resolve=>require(["../components/blank.vue"],resolve),
          children:[
            {
              path:'date',
              name:'南瓜-date',
              component:resolve=>require(["../components/date.vue"],resolve),
            },
            {
              path:'month',
              name:'南瓜-month',
              component:resolve=>require(["../components/month.vue"],resolve),
            },
            {
              path:'monthly',
              name:'南瓜-monthly',
              component:resolve=>require(["../components/monthly.vue"],resolve),
            }
          ]
        },{
          path:'/dg',
          redirect:'/dg/date',
          name:"冬瓜",
          component:resolve=>require(["../components/blank.vue"],resolve),
          children:[
            {
              path:'date',
              name:'冬瓜-date',
              component:resolve=>require(["../components/date.vue"],resolve),
            },
            {
              path:'month',
              name:'冬瓜-month',
              component:resolve=>require(["../components/month.vue"],resolve),
            },
            {
              path:'monthly',
              name:'冬瓜-monthly',
              component:resolve=>require(["../components/monthly.vue"],resolve),
            }
          ]
        },{
          path:'/sld',
          redirect:'/sld/date',
          name:"水龍豆",
          component:resolve=>require(["../components/blank.vue"],resolve),
          children:[
            {
              path:'date',
              name:'水龍豆-date',
              component:resolve=>require(["../components/date.vue"],resolve),
            },
            {
              path:'month',
              name:'水龍豆-month',
              component:resolve=>require(["../components/month.vue"],resolve),
            },
            {
              path:'monthly',
              name:'水龍豆-monthly',
              component:resolve=>require(["../components/monthly.vue"],resolve),
            }
          ]
        },{
          path:'/dd',
          redirect:'/dd/date',
          name:"刀豆",
          component:resolve=>require(["../components/blank.vue"],resolve),
          children:[
            {
              path:'date',
              name:'刀豆-date',
              component:resolve=>require(["../components/date.vue"],resolve),
            },
            {
              path:'month',
              name:'刀豆-month',
              component:resolve=>require(["../components/month.vue"],resolve),
            },
            {
              path:'monthly',
              name:'刀豆-monthly',
              component:resolve=>require(["../components/monthly.vue"],resolve),
            }
          ]
        },{
          path:'/fsg',
          redirect:'/fsg/date',
          name:"佛手瓜",
          component:resolve=>require(["../components/blank.vue"],resolve),
          children:[
            {
              path:'date',
              name:'佛手瓜-date',
              component:resolve=>require(["../components/date.vue"],resolve),
            },
            {
              path:'month',
              name:'佛手瓜-month',
              component:resolve=>require(["../components/month.vue"],resolve),
            },
            {
              path:'monthly',
              name:'佛手瓜-monthly',
              component:resolve=>require(["../components/monthly.vue"],resolve),
            }
          ]
        },{
          path:'/jd',
          redirect:'/jd/date',
          name:"豇豆",
          component:resolve=>require(["../components/blank.vue"],resolve),
          children:[
            {
              path:'date',
              name:'豇豆-date',
              component:resolve=>require(["../components/date.vue"],resolve),
            },
            {
              path:'month',
              name:'豇豆-month',
              component:resolve=>require(["../components/month.vue"],resolve),
            },
            {
              path:'monthly',
              name:'豇豆-monthly',
              component:resolve=>require(["../components/monthly.vue"],resolve),
            }
          ]
        },{
          path:'/hlhg',
          redirect:'/hlhg/date',
          name:"荷兰黄瓜",
          component:resolve=>require(["../components/blank.vue"],resolve),
          children:[
            {
              path:'date',
              name:'荷兰黄瓜-date',
              component:resolve=>require(["../components/date.vue"],resolve),
            },
            {
              path:'month',
              name:'荷兰黄瓜-month',
              component:resolve=>require(["../components/month.vue"],resolve),
            },
            {
              path:'monthly',
              name:'荷兰黄瓜-monthly',
              component:resolve=>require(["../components/monthly.vue"],resolve),
            }
          ]
        },{
          path:'/hq',
          redirect:'/hq/date',
          name:"杭茄",
          component:resolve=>require(["../components/blank.vue"],resolve),
          children:[
            {
              path:'date',
              name:'杭茄-date',
              component:resolve=>require(["../components/date.vue"],resolve),
            },
            {
              path:'month',
              name:'杭茄-month',
              component:resolve=>require(["../components/month.vue"],resolve),
            },
            {
              path:'monthly',
              name:'杭茄-monthly',
              component:resolve=>require(["../components/monthly.vue"],resolve),
            }
          ]
        },

      ]
    },    {
      path: '/',
      name: '上根茎',
      component: Index,
      redirect:'/jb',
      children:[
        {
          path:'/jb',
          redirect:'/jb/date',
          name:"茭白",
          component:resolve=>require(["../components/blank.vue"],resolve),
          children:[
            {
              path:'date',
              name:'茭白-date',
              component:resolve=>require(["../components/date.vue"],resolve),
            },
            {
              path:'month',
              name:'茭白-month',
              component:resolve=>require(["../components/month.vue"],resolve),
            },
            {
              path:'monthly',
              name:'茭白-monthly',
              component:resolve=>require(["../components/monthly.vue"],resolve),
            }
          ]
        },{
          path:'/ws',
          redirect:'/ws/date',
          name:"莴笋",
          component:resolve=>require(["../components/blank.vue"],resolve),
          children:[
            {
              path:'date',
              name:'莴笋-date',
              component:resolve=>require(["../components/date.vue"],resolve),
            },
            {
              path:'month',
              name:'莴笋-month',
              component:resolve=>require(["../components/month.vue"],resolve),
            },
            {
              path:'monthly',
              name:'莴笋-monthly',
              component:resolve=>require(["../components/monthly.vue"],resolve),
            }
          ]
        },{
          path:'/qinc',
          redirect:'/qinc/date',
          name:"芹菜",
          component:resolve=>require(["../components/blank.vue"],resolve),
          children:[
            {
              path:'date',
              name:'芹菜-date',
              component:resolve=>require(["../components/date.vue"],resolve),
            },
            {
              path:'month',
              name:'芹菜-month',
              component:resolve=>require(["../components/month.vue"],resolve),
            },
            {
              path:'monthly',
              name:'芹菜-monthly',
              component:resolve=>require(["../components/monthly.vue"],resolve),
            }
          ]
        },{
          path:'/xq',
          redirect:'/xq/date',
          name:"西芹",
          component:resolve=>require(["../components/blank.vue"],resolve),
          children:[
            {
              path:'date',
              name:'西芹-date',
              component:resolve=>require(["../components/date.vue"],resolve),
            },
            {
              path:'month',
              name:'西芹-month',
              component:resolve=>require(["../components/month.vue"],resolve),
            },
            {
              path:'monthly',
              name:'西芹-monthly',
              component:resolve=>require(["../components/monthly.vue"],resolve),
            }
          ]
        },{
          path:'/dc',
          redirect:'/dc/date',
          name:"大蔥",
          component:resolve=>require(["../components/blank.vue"],resolve),
          children:[
            {
              path:'date',
              name:'大蔥-date',
              component:resolve=>require(["../components/date.vue"],resolve),
            },
            {
              path:'month',
              name:'大蔥-month',
              component:resolve=>require(["../components/month.vue"],resolve),
            },
            {
              path:'monthly',
              name:'大蔥-monthly',
              component:resolve=>require(["../components/monthly.vue"],resolve),
            }
          ]
        },
      ]      
    },    {
      path: '/',
      name: '下根茎',
      component: Index,
      redirect:'/hlb',
      children:[
        {
          path:'/hlb',
          redirect:'/hlb/date',
          name:"胡萝卜",
          component:resolve=>require(["../components/blank.vue"],resolve),
          children:[
            {
              path:'date',
              name:'胡萝卜-date',
              component:resolve=>require(["../components/date.vue"],resolve),
            },
            {
              path:'month',
              name:'胡萝卜-month',
              component:resolve=>require(["../components/month.vue"],resolve),
            },
            {
              path:'monthly',
              name:'胡萝卜-monthly',
              component:resolve=>require(["../components/monthly.vue"],resolve),
            }
          ]
        },{
          path:'/blb',
          redirect:'/blb/date',
          name:"白萝卜",
          component:resolve=>require(["../components/blank.vue"],resolve),
          children:[
            {
              path:'date',
              name:'白萝卜-date',
              component:resolve=>require(["../components/date.vue"],resolve),
            },
            {
              path:'month',
              name:'白萝卜-month',
              component:resolve=>require(["../components/month.vue"],resolve),
            },
            {
              path:'monthly',
              name:'白萝卜-monthly',
              component:resolve=>require(["../components/monthly.vue"],resolve),
            }
          ]
        },{
          path:'/qlb',
          redirect:'/qlb/date',
          name:"青萝卜",
          component:resolve=>require(["../components/blank.vue"],resolve),
          children:[
            {
              path:'date',
              name:'青萝卜-date',
              component:resolve=>require(["../components/date.vue"],resolve),
            },
            {
              path:'month',
              name:'青萝卜-month',
              component:resolve=>require(["../components/month.vue"],resolve),
            },
            {
              path:'monthly',
              name:'青萝卜-monthly',
              component:resolve=>require(["../components/monthly.vue"],resolve),
            }
          ]
        },{
          path:'/yt',
          redirect:'/yt/date',
          name:"芋头",
          component:resolve=>require(["../components/blank.vue"],resolve),
          children:[
            {
              path:'date',
              name:'芋头-date',
              component:resolve=>require(["../components/date.vue"],resolve),
            },
            {
              path:'month',
              name:'芋头-month',
              component:resolve=>require(["../components/month.vue"],resolve),
            },
            {
              path:'monthly',
              name:'芋头-monthly',
              component:resolve=>require(["../components/monthly.vue"],resolve),
            }
          ]
        },{
          path:'/zs',
          redirect:'/zs/date',
          name:"紫薯",
          component:resolve=>require(["../components/blank.vue"],resolve),
          children:[
            {
              path:'date',
              name:'紫薯-date',
              component:resolve=>require(["../components/date.vue"],resolve),
            },
            {
              path:'month',
              name:'紫薯-month',
              component:resolve=>require(["../components/month.vue"],resolve),
            },
            {
              path:'monthly',
              name:'紫薯-monthly',
              component:resolve=>require(["../components/monthly.vue"],resolve),
            }
          ]
        },{
          path:'/qs',
          redirect:'/qs/date',
          name:"青蒜",
          component:resolve=>require(["../components/blank.vue"],resolve),
          children:[
            {
              path:'date',
              name:'青蒜-date',
              component:resolve=>require(["../components/date.vue"],resolve),
            },
            {
              path:'month',
              name:'青蒜-month',
              component:resolve=>require(["../components/month.vue"],resolve),
            },
            {
              path:'monthly',
              name:'青蒜-monthly',
              component:resolve=>require(["../components/monthly.vue"],resolve),
            }
          ]
        },{
          path:'/ls',
          redirect:'/ls/date',
          name:"芦笋",
          component:resolve=>require(["../components/blank.vue"],resolve),
          children:[
            {
              path:'date',
              name:'芦笋-date',
              component:resolve=>require(["../components/date.vue"],resolve),
            },
            {
              path:'month',
              name:'芦笋-month',
              component:resolve=>require(["../components/month.vue"],resolve),
            },
            {
              path:'monthly',
              name:'芦笋-monthly',
              component:resolve=>require(["../components/monthly.vue"],resolve),
            }
          ]
        },{
          path:'/td',
          redirect:'/td/date',
          name:"土豆",
          component:resolve=>require(["../components/blank.vue"],resolve),
          children:[
            {
              path:'date',
              name:'土豆-date',
              component:resolve=>require(["../components/date.vue"],resolve),
            },
            {
              path:'month',
              name:'土豆-month',
              component:resolve=>require(["../components/month.vue"],resolve),
            },
            {
              path:'monthly',
              name:'土豆-monthly',
              component:resolve=>require(["../components/monthly.vue"],resolve),
            }
          ]
        },{
          path:'/hs',
          redirect:'/hs/date',
          name:"红薯",
          component:resolve=>require(["../components/blank.vue"],resolve),
          children:[
            {
              path:'date',
              name:'红薯-date',
              component:resolve=>require(["../components/date.vue"],resolve),
            },
            {
              path:'month',
              name:'红薯-month',
              component:resolve=>require(["../components/month.vue"],resolve),
            },
            {
              path:'monthly',
              name:'红薯-monthly',
              component:resolve=>require(["../components/monthly.vue"],resolve),
            }
          ]
        },{
          path:'/yn',
          redirect:'/hs/date',
          name:"芋艿",
          component:resolve=>require(["../components/blank.vue"],resolve),
          children:[
            {
              path:'date',
              name:'芋艿-date',
              component:resolve=>require(["../components/date.vue"],resolve),
            },
            {
              path:'month',
              name:'芋艿-month',
              component:resolve=>require(["../components/month.vue"],resolve),
            },
            {
              path:'monthly',
              name:'芋艿-monthly',
              component:resolve=>require(["../components/monthly.vue"],resolve),
            }
          ]
        },{
          path:'/st',
          redirect:'/st/date',
          name:"蒜头",
          component:resolve=>require(["../components/blank.vue"],resolve),
          children:[
            {
              path:'date',
              name:'蒜头-date',
              component:resolve=>require(["../components/date.vue"],resolve),
            },
            {
              path:'month',
              name:'蒜头-month',
              component:resolve=>require(["../components/month.vue"],resolve),
            },
            {
              path:'monthly',
              name:'蒜头-monthly',
              component:resolve=>require(["../components/monthly.vue"],resolve),
            }
          ]
        },{
          path:'/yc',
          redirect:'/yc/date',
          name:"洋葱",
          component:resolve=>require(["../components/blank.vue"],resolve),
          children:[
            {
              path:'date',
              name:'洋葱-date',
              component:resolve=>require(["../components/date.vue"],resolve),
            },
            {
              path:'month',
              name:'洋葱-month',
              component:resolve=>require(["../components/month.vue"],resolve),
            },
            {
              path:'monthly',
              name:'洋葱-monthly',
              component:resolve=>require(["../components/monthly.vue"],resolve),
            }
          ]
        },{
          path:'/md',
          redirect:'/md/date',
          name:"毛豆",
          component:resolve=>require(["../components/blank.vue"],resolve),
          children:[
            {
              path:'date',
              name:'毛豆-date',
              component:resolve=>require(["../components/date.vue"],resolve),
            },
            {
              path:'month',
              name:'毛豆-month',
              component:resolve=>require(["../components/month.vue"],resolve),
            },
            {
              path:'monthly',
              name:'毛豆-monthly',
              component:resolve=>require(["../components/monthly.vue"],resolve),
            }
          ]
        },
      ]
    },    {
      path: '/',
      name: '结球',
      component: Index,
      redirect:'/jxc',
      children:[
        {
          path:'/jxc',
          redirect:'/jxc/date',
          name:"卷心菜",
          component:resolve=>require(["../components/blank.vue"],resolve),
          children:[
            {
              path:'date',
              name:'卷心菜-date',
              component:resolve=>require(["../components/date.vue"],resolve),
            },
            {
              path:'month',
              name:'卷心菜-month',
              component:resolve=>require(["../components/month.vue"],resolve),
            },
            {
              path:'monthly',
              name:'卷心菜-monthly',
              component:resolve=>require(["../components/monthly.vue"],resolve),
            }
          ]
        },{
          path:'/zgl',
          redirect:'/zgl/date',
          name:"紫甘蓝",
          component:resolve=>require(["../components/blank.vue"],resolve),
          children:[
            {
              path:'date',
              name:'紫甘蓝-date',
              component:resolve=>require(["../components/date.vue"],resolve),
            },
            {
              path:'month',
              name:'紫甘蓝-month',
              component:resolve=>require(["../components/month.vue"],resolve),
            },
            {
              path:'monthly',
              name:'紫甘蓝-monthly',
              component:resolve=>require(["../components/monthly.vue"],resolve),
            }
          ]
        },{
          path:'/wwc',
          redirect:'/wwc/date',
          name:"娃娃菜",
          component:resolve=>require(["../components/blank.vue"],resolve),
          children:[
            {
              path:'date',
              name:'娃娃菜-date',
              component:resolve=>require(["../components/date.vue"],resolve),
            },
            {
              path:'month',
              name:'娃娃菜-month',
              component:resolve=>require(["../components/month.vue"],resolve),
            },
            {
              path:'monthly',
              name:'娃娃菜-monthly',
              component:resolve=>require(["../components/monthly.vue"],resolve),
            }
          ]
        },{
          path:'/dbc',
          redirect:'/dbc/date',
          name:"大白菜",
          component:resolve=>require(["../components/blank.vue"],resolve),
          children:[
            {
              path:'date',
              name:'大白菜-date',
              component:resolve=>require(["../components/date.vue"],resolve),
            },
            {
              path:'month',
              name:'大白菜-month',
              component:resolve=>require(["../components/month.vue"],resolve),
            },
            {
              path:'monthly',
              name:'大白菜-monthly',
              component:resolve=>require(["../components/monthly.vue"],resolve),
            }
          ]
        },{
          path:'/xlh',
          redirect:'/xlh/date',
          name:"西兰花",
          component:resolve=>require(["../components/blank.vue"],resolve),
          children:[
            {
              path:'date',
              name:'西兰花-date',
              component:resolve=>require(["../components/date.vue"],resolve),
            },
            {
              path:'month',
              name:'西兰花-month',
              component:resolve=>require(["../components/month.vue"],resolve),
            },
            {
              path:'monthly',
              name:'西兰花-monthly',
              component:resolve=>require(["../components/monthly.vue"],resolve),
            }
          ]
        },{
          path:'/hc',
          redirect:'/hc/date',
          name:"花菜",
          component:resolve=>require(["../components/blank.vue"],resolve),
          children:[
            {
              path:'date',
              name:'花菜-date',
              component:resolve=>require(["../components/date.vue"],resolve),
            },
            {
              path:'month',
              name:'花菜-month',
              component:resolve=>require(["../components/month.vue"],resolve),
            },
            {
              path:'monthly',
              name:'花菜-monthly',
              component:resolve=>require(["../components/monthly.vue"],resolve),
            }
          ]
        },{
          path:'/qgl',
          redirect:'/qgl/date',
          name:"青甘蓝",
          component:resolve=>require(["../components/blank.vue"],resolve),
          children:[
            {
              path:'date',
              name:'青甘蓝-date',
              component:resolve=>require(["../components/date.vue"],resolve),
            },
            {
              path:'month',
              name:'青甘蓝-month',
              component:resolve=>require(["../components/month.vue"],resolve),
            },
            {
              path:'monthly',
              name:'青甘蓝-monthly',
              component:resolve=>require(["../components/monthly.vue"],resolve),
            }
          ]
        },{
          path:'/dwwc',
          redirect:'/dwwc/date',
          name:"大娃娃菜",
          component:resolve=>require(["../components/blank.vue"],resolve),
          children:[
            {
              path:'date',
              name:'大娃娃菜-date',
              component:resolve=>require(["../components/date.vue"],resolve),
            },
            {
              path:'month',
              name:'大娃娃菜-month',
              component:resolve=>require(["../components/month.vue"],resolve),
            },
            {
              path:'monthly',
              name:'大娃娃菜-monthly',
              component:resolve=>require(["../components/monthly.vue"],resolve),
            }
          ]
        },
      ]
    },
  ],
  mode:'history'
})
